monitor.bluez.properties = {
  bluez5.enable-midi = false
  bluez5.enable-hw-volume = true
  bluez5.roles = [ a2dp_sink a2dp_source hfp_hf hfp_ag ]
  bluez5.codecs = [ ldac aptx aptx_hd sbc ]
  bluez5.hfphsp-backend = "native"
}
