monitor.bluez.properties = {
  bluez5.roles = [ a2dp_sink a2dp_source hfp_hf hfp_ag ]
  bluez5.codecs = [ ldac aptx aptx_hd sbc ]
  bluez5.default.rate = 48000
  bluez5.default.channels = 2
  bluez5.enable-midi = false
  bluez5.enable-hw-volume = true
  bluez5.hfphsp-backend = "native"
  bluez5.auto-connect = [ a2dp_sink hfp_hf ]
}

monitor.bluez.rules = [
  {
    matches = [
      { device.name = "~bluez_card.*80_99_E7_9B_E2_80.*" }
    ]
    actions = {
      update-props = {
        bluez5.auto-connect = [ a2dp_sink ]
        bluez5.hw-volume = [ a2dp_sink ]
        api.bluez5.codec = "ldac"
        device.description = "Sony WH-1000XM4"
        device.nick = "Sony WH-1000XM4"
        session.suspend-timeout-seconds = 0
      }
    }
  },
  {
    matches = [
      { device.name = "~bluez_card.*" }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
