#!/usr/bin/env bash
# =============================================================================
# Terminal Color Applicator
# =============================================================================
# Reloads Foot terminals to apply new colors from colors.ini
# Colors are automatically generated by matugen and included in Foot config
#
# Dependencies: foot
# =============================================================================

# Reload foot terminals by sending SIGUSR1
# This tells Foot to reload its config, picking up new colors from colors.ini
pkill -SIGUSR1 foot 2>/dev/null

echo "Terminal colors reloaded"
