#!/usr/bin/env bash
# =============================================================================
# GTK Settings Synchronization
# =============================================================================
# Syncs GTK theme settings from settings.ini to gsettings and Hyprland cursor
# Ensures consistent theming across GTK applications, GNOME apps, and Hyprland
#
# Dependencies: gsettings, hyprctl
# =============================================================================

set -euo pipefail

# Configuration
GTK_CONFIG="$HOME/.config/gtk-3.0/settings.ini"
CURSOR_CONF="$HOME/.config/hypr/conf/cursor.conf"
LOG_FILE="$HOME/.local/state/gtk-sync.log"

# Ensure log directory exists
mkdir -p "$(dirname "$LOG_FILE")"

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') $*" | tee -a "$LOG_FILE"
}

# Check that GTK settings file exists
if [[ ! -f "$GTK_CONFIG" ]]; then
    log "ERROR: GTK settings file not found: $GTK_CONFIG"
    exit 1
fi

log "Starting GTK settings synchronization..."

# Read settings from GTK config file
gnome_schema="org.gnome.desktop.interface"
gtk_theme="$(grep 'gtk-theme-name' "$GTK_CONFIG" | sed 's/.*=\s*//' | tr -d '\r')"
icon_theme="$(grep 'gtk-icon-theme-name' "$GTK_CONFIG" | sed 's/.*=\s*//' | tr -d '\r')"
cursor_theme="$(grep 'gtk-cursor-theme-name' "$GTK_CONFIG" | sed 's/.*=\s*//' | tr -d '\r')"
cursor_size="$(grep 'gtk-cursor-theme-size' "$GTK_CONFIG" | sed 's/.*=\s*//' | tr -d '\r')"
font_name="$(grep 'gtk-font-name' "$GTK_CONFIG" | sed 's/.*=\s*//' | tr -d '\r')"
prefer_dark_theme="$(grep 'gtk-application-prefer-dark-theme' "$GTK_CONFIG" | sed 's/.*=\s*//' | tr -d '\r')"

# Validate that we got values
if [[ -z "$gtk_theme" ]]; then
    log "WARNING: Could not read gtk-theme-name from config"
fi

# Echo values for debugging
log "GTK Theme: $gtk_theme"
log "Icon Theme: $icon_theme"
log "Cursor Theme: $cursor_theme"
log "Cursor Size: $cursor_size"
log "Font Name: $font_name"

# Determine color scheme preference
if [[ "$prefer_dark_theme" == "0" ]]; then
    color_scheme="prefer-light"
else
    color_scheme="prefer-dark"
fi
log "Color Scheme: $color_scheme"

# Update gsettings for GTK apps
log "Updating gsettings..."
if command -v gsettings >/dev/null 2>&1; then
    gsettings set "$gnome_schema" gtk-theme "$gtk_theme" 2>/dev/null || log "WARNING: Failed to set gtk-theme"
    gsettings set "$gnome_schema" icon-theme "$icon_theme" 2>/dev/null || log "WARNING: Failed to set icon-theme"
    gsettings set "$gnome_schema" cursor-theme "$cursor_theme" 2>/dev/null || log "WARNING: Failed to set cursor-theme"
    gsettings set "$gnome_schema" font-name "$font_name" 2>/dev/null || log "WARNING: Failed to set font-name"
    gsettings set "$gnome_schema" color-scheme "$color_scheme" 2>/dev/null || log "WARNING: Failed to set color-scheme"
    log "gsettings updated successfully"
else
    log "WARNING: gsettings not found, skipping GNOME settings sync"
fi

# Update Hyprland cursor configuration
if [[ -n "$cursor_theme" ]] && [[ -n "$cursor_size" ]]; then
    log "Updating Hyprland cursor configuration..."

    # Create cursor.conf with proper formatting
    cat > "$CURSOR_CONF" <<EOF
# -----------------------------------------------------
# Cursor Configuration
# Auto-generated by gtk_sync.sh
# Last Updated: $(date '+%Y-%m-%d %H:%M:%S')
# -----------------------------------------------------

exec-once = hyprctl setcursor $cursor_theme $cursor_size
EOF

    # Apply cursor settings to current Hyprland session
    if command -v hyprctl >/dev/null 2>&1; then
        hyprctl setcursor "$cursor_theme" "$cursor_size" 2>/dev/null && \
            log "Cursor updated in Hyprland: $cursor_theme $cursor_size" || \
            log "WARNING: Failed to update Hyprland cursor"
    else
        log "WARNING: hyprctl not available, cursor will update on next login"
    fi
else
    log "WARNING: Cursor theme or size not found in GTK config"
fi

log "GTK settings synchronization complete"
