#!/usr/bin/env bash
# =============================================================================
# IDE Focus Fix
# =============================================================================
# Fixes JetBrains IDE focus stealing and popup issues in Hyprland
# Applies IDE properties and window rules for proper focus behavior
#
# Dependencies: hyprctl
# =============================================================================

set -euo pipefail

readonly SCRIPT_NAME="fix-ide-focus"
readonly LOG_FILE="$HOME/.local/state/hyprland-ide-focus.log"
readonly RUSTOVER_PROPERTIES_DIR="$HOME/.local/share/JetBrains"

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $*" | tee -a "$LOG_FILE"
}

# Find RustRover installation directory
find_rustover_dir() {
    local rustover_dir
    rustover_dir=$(find "$RUSTOVER_PROPERTIES_DIR" -maxdepth 1 -type d -name "RustRover*" 2>/dev/null | head -1)
    
    if [[ -n "$rustover_dir" ]]; then
        echo "$rustover_dir"
        return 0
    else
        log "WARNING: RustRover installation directory not found"
        return 1
    fi
}

# Apply IDE-specific properties
configure_rustover_properties() {
    local rustover_dir
    if ! rustover_dir=$(find_rustover_dir); then
        log "Skipping RustRover properties configuration - installation not found"
        return 0
    fi
    
    local properties_file="$rustover_dir/idea.properties"
    log "Configuring RustRover properties: $properties_file"
    
    # Create properties directory if it doesn't exist
    mkdir -p "$(dirname "$properties_file")"
    
    # Apply focus fix properties
    cat > "$properties_file" << 'EOF'
# Hyprland Focus Fix Configuration for RustRover
# Purpose: Prevent focus stealing and improve popup behavior
# Generated by fix_ide_focus.sh

# Disable focus stealing mechanisms
suppress.focus.stealing=true  
suppress.focus.stealing.auto.request.focus=true
suppress.focus.stealing.active.window.checks=true
suppress.focus.stealing.disable.auto.request.focus=true

# Improve popup behavior
popup.animation.enabled=false
ide.popup.resizable=true

# Wayland optimizations
awt.nativeDoubleBuffering=true
sun.java2d.xrender=false
sun.java2d.noddraw=true

# Prevent unnecessary focus changes
ide.windowSystem.autoRequestFocus=false
ide.powersave.mode=false

# Additional Wayland stability
sun.java2d.opengl=false
java2d.metal=false
EOF
    
    log "RustRover properties configured successfully"
}

# Apply Hyprland window rules
apply_window_rules() {
    log "Reloading Hyprland configuration"
    
    if hyprctl reload >/dev/null 2>&1; then
        log "Hyprland configuration reloaded successfully"
        
        # Verify rules are active
        local jetbrains_rules
        jetbrains_rules=$(hyprctl getoption windowrule | grep -c "jetbrains\|RustRover" || echo "0")
        log "Active JetBrains window rules: $jetbrains_rules"
    else
        log "ERROR: Failed to reload Hyprland configuration"
        return 1
    fi
}

# Check for running JetBrains processes
check_ide_processes() {
    local running_ides
    running_ides=$(pgrep -f "jetbrains-|RustRover" | wc -l)
    
    if [[ "$running_ides" -gt 0 ]]; then
        log "Found $running_ides running JetBrains IDE process(es)"
        echo "Please restart your JetBrains IDEs to apply new focus settings"
        return 0
    else
        log "No JetBrains IDE processes currently running"
        return 0
    fi
}

# Show status of focus fixes
show_status() {
    log "=== IDE Focus Fix Status ==="
    
    # Check if window rules are loaded
    if hyprctl getoption windowrule | grep -q "jetbrains\|RustRover"; then
        echo "✓ JetBrains window rules are active"
    else
        echo "✗ JetBrains window rules not found"
    fi
    
    # Check if properties exist
    local rustover_dir
    if rustover_dir=$(find_rustover_dir) && [[ -f "$rustover_dir/idea.properties" ]]; then
        echo "✓ RustRover properties configured"
    else
        echo "✗ RustRover properties not configured"
    fi
    
    # Check for running processes
    check_ide_processes
}

# Main function
main() {
    case "${1:-apply}" in
        "apply")
            log "Starting IDE focus fix application"
            configure_rustover_properties
            apply_window_rules
            check_ide_processes
            log "IDE focus fix completed"
            ;;
        "status")
            show_status
            ;;
        "reload")
            apply_window_rules
            ;;
        *)
            echo "Usage: $0 [apply|status|reload]"
            echo "  apply  - Apply all focus fixes (default)"
            echo "  status - Show current status"
            echo "  reload - Reload Hyprland configuration only"
            exit 1
            ;;
    esac
}

main "$@"
