# Hyprpaper Configuration - Argonaut Desktop

preload = /home/barhamm/Pictures/Wallpapers/3840x2160-dark-archlinux.png
wallpaper = DP-3,/home/barhamm/Pictures/Wallpapers/3840x2160-dark-archlinux.png
splash = false
