#==========================================================#
#                     GROUP CONFIGURATION                  #
#==========================================================#
# File: group.conf
# Purpose: Group settings
# Last Updated: 2025-07-18
# Documentation: https://wiki.hyprland.org/Configuring/Variables/#group
#==========================================================#

