# Layer Rules Configuration

#------------------------- WAYBAR -------------------------#
layerrule = match:namespace waybar, no_anim on

#---------------- SWAYNC (NOTIFICATION CENTER) ------------#
layerrule = match:namespace swaync-control-center, blur on
layerrule = match:namespace swaync-control-center, ignore_alpha 0.0
layerrule = match:namespace swaync-control-center, animation slide

layerrule = match:namespace swaync-notification-window, blur_popups on
layerrule = match:namespace swaync-notification-window, order 100
layerrule = match:namespace swaync-notification-window, ignore_alpha 0.0
layerrule = match:namespace swaync-notification-window, animation slide
