# Layout Configuration - Argonaut Desktop
# No touchpad gestures (desktop)

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
}

binds {
    workspace_back_and_forth = true
    allow_workspace_cycles = true
    pass_mouse_when_bound = false
}
