# Misc Settings

misc {
    disable_hyprland_logo = true
    col.splash = 0x665c54
    splash_font_family = Iosevka NF Propo
    force_default_wallpaper = 0

    focus_on_activate = false
    mouse_move_enables_dpms = false
    key_press_enables_dpms = false

    animate_manual_resizes = false
    animate_mouse_windowdragging = false

    initial_workspace_tracking = 1
}

ecosystem {
    no_donation_nag = true
}

xwayland {
    force_zero_scaling = true
}
