# Monitor Configuration - Argonaut Desktop
# Single 4K TV on DP-3
# or, Single 1440p 120hz monitor

# Primary display - 4K@60Hz, scale 2.0, 10-bit color for HDR
monitor = DP-3, 3840x2160@60, auto, 2.0, bitdepth, 10

# Primary display - 4K@60Hz, scale 2.0, 10-bit color for HDR
monitor = DP-2, 2560x1440@120, auto, 1.0, bitdepth, 8, vrr, 2

# Fallback for any other monitor
monitor = , preferred, auto, 1.0
